FROM python:3.8

RUN apt-get update -y && apt-get upgrade -y

WORKDIR /usr/src/app

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY . .


CMD [ "uvicorn", "main:app", "--reload" ]